// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Persistence.Database;

#nullable disable

namespace User.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("User")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("User.Domain.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatoTarget")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdMenuPadre")
                        .HasColumnType("int");

                    b.Property<string>("NombreMenu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("RutaArbol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RutaImagen")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RutaPagina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoIcono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("IdMenu");

                    b.ToTable("Menus", "User");

                    b.HasData(
                        new
                        {
                            IdMenu = 1,
                            Activo = true,
                            Clase = "",
                            DatoTarget = "",
                            Descripcion = "Menu de Usuarios Web Empresarial",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1145),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1156),
                            Icono = "",
                            IdMenuPadre = 0,
                            NombreMenu = "Nodo 0 - Menu Web Empresarial",
                            Orden = 0,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "",
                            TipoIcono = "",
                            Visible = false
                        },
                        new
                        {
                            IdMenu = 2,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Tablero de control",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1161),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1161),
                            Icono = "layers",
                            IdMenuPadre = 0,
                            NombreMenu = "Tablero de control",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main/dashboard",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 3,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Clientes",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1164),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1164),
                            Icono = "layers",
                            IdMenuPadre = 0,
                            NombreMenu = "Clientes",
                            Orden = 2,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 4,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Nuevo",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1166),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1167),
                            Icono = "add",
                            IdMenuPadre = 3,
                            NombreMenu = "Nuevo",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 5,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Lista",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1169),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1169),
                            Icono = "list",
                            IdMenuPadre = 3,
                            NombreMenu = "Lista",
                            Orden = 2,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 6,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Productos",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1173),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1173),
                            Icono = "layers",
                            IdMenuPadre = 0,
                            NombreMenu = "Productos",
                            Orden = 3,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 7,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Nuevo",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1175),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1175),
                            Icono = "add",
                            IdMenuPadre = 6,
                            NombreMenu = "Nuevo",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 8,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Lista",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1177),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1177),
                            Icono = "list",
                            IdMenuPadre = 6,
                            NombreMenu = "Lista",
                            Orden = 2,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 9,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Seguridad",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1179),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1179),
                            Icono = "layers",
                            IdMenuPadre = 0,
                            NombreMenu = "Seguridad",
                            Orden = 4,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 10,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Usuarios",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1181),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1182),
                            Icono = "layers",
                            IdMenuPadre = 9,
                            NombreMenu = "Usuarios",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 11,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Nuevo",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1184),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1184),
                            Icono = "add",
                            IdMenuPadre = 10,
                            NombreMenu = "Nuevo",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 12,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Lista",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1186),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1186),
                            Icono = "add",
                            IdMenuPadre = 10,
                            NombreMenu = "Lista",
                            Orden = 2,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 13,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Menus",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1188),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1188),
                            Icono = "layers",
                            IdMenuPadre = 9,
                            NombreMenu = "Menus",
                            Orden = 2,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 14,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Nuevo",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1189),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1190),
                            Icono = "add",
                            IdMenuPadre = 13,
                            NombreMenu = "Nuevo",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 15,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Lista",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1191),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1192),
                            Icono = "list",
                            IdMenuPadre = 13,
                            NombreMenu = "Lista",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 16,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Menus por rol",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1193),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1193),
                            Icono = "layers",
                            IdMenuPadre = 13,
                            NombreMenu = "Menus por rol",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 17,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Lista",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1196),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1196),
                            Icono = "list",
                            IdMenuPadre = 16,
                            NombreMenu = "Lista",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 18,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Roles",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1199),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1199),
                            Icono = "layers",
                            IdMenuPadre = 9,
                            NombreMenu = "Roles",
                            Orden = 3,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 19,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Nuevo",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1201),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1201),
                            Icono = "add",
                            IdMenuPadre = 18,
                            NombreMenu = "Nuevo",
                            Orden = 1,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        },
                        new
                        {
                            IdMenu = 20,
                            Activo = true,
                            Clase = "glyphicon glyphicon-user position-left",
                            DatoTarget = "",
                            Descripcion = "Lista",
                            FechaCreado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1203),
                            FechaModificado = new DateTime(2022, 11, 3, 16, 29, 43, 354, DateTimeKind.Local).AddTicks(1203),
                            Icono = "list",
                            IdMenuPadre = 18,
                            NombreMenu = "Lista",
                            Orden = 2,
                            RutaArbol = "",
                            RutaImagen = "",
                            RutaPagina = "main",
                            TipoIcono = "father-icon",
                            Visible = true
                        });
                });

            modelBuilder.Entity("User.Domain.MenuModule", b =>
                {
                    b.Property<int>("IdMenuModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenuModule"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.HasKey("IdMenuModule");

                    b.ToTable("MenuModules", "User");

                    b.HasData(
                        new
                        {
                            IdMenuModule = 1,
                            Activo = true,
                            IdMenu = 1,
                            IdModule = 0
                        },
                        new
                        {
                            IdMenuModule = 2,
                            Activo = true,
                            IdMenu = 2,
                            IdModule = 1
                        },
                        new
                        {
                            IdMenuModule = 3,
                            Activo = true,
                            IdMenu = 3,
                            IdModule = 2
                        },
                        new
                        {
                            IdMenuModule = 4,
                            Activo = true,
                            IdMenu = 4,
                            IdModule = 2
                        },
                        new
                        {
                            IdMenuModule = 5,
                            Activo = true,
                            IdMenu = 5,
                            IdModule = 2
                        },
                        new
                        {
                            IdMenuModule = 6,
                            Activo = true,
                            IdMenu = 6,
                            IdModule = 3
                        },
                        new
                        {
                            IdMenuModule = 7,
                            Activo = true,
                            IdMenu = 7,
                            IdModule = 3
                        },
                        new
                        {
                            IdMenuModule = 8,
                            Activo = true,
                            IdMenu = 8,
                            IdModule = 3
                        },
                        new
                        {
                            IdMenuModule = 9,
                            Activo = true,
                            IdMenu = 9,
                            IdModule = 4
                        },
                        new
                        {
                            IdMenuModule = 10,
                            Activo = true,
                            IdMenu = 10,
                            IdModule = 5
                        },
                        new
                        {
                            IdMenuModule = 11,
                            Activo = true,
                            IdMenu = 11,
                            IdModule = 5
                        },
                        new
                        {
                            IdMenuModule = 12,
                            Activo = true,
                            IdMenu = 12,
                            IdModule = 5
                        },
                        new
                        {
                            IdMenuModule = 13,
                            Activo = true,
                            IdMenu = 13,
                            IdModule = 6
                        },
                        new
                        {
                            IdMenuModule = 14,
                            Activo = true,
                            IdMenu = 14,
                            IdModule = 6
                        },
                        new
                        {
                            IdMenuModule = 15,
                            Activo = true,
                            IdMenu = 15,
                            IdModule = 6
                        },
                        new
                        {
                            IdMenuModule = 16,
                            Activo = true,
                            IdMenu = 16,
                            IdModule = 7
                        },
                        new
                        {
                            IdMenuModule = 17,
                            Activo = true,
                            IdMenu = 17,
                            IdModule = 7
                        },
                        new
                        {
                            IdMenuModule = 18,
                            Activo = true,
                            IdMenu = 18,
                            IdModule = 8
                        },
                        new
                        {
                            IdMenuModule = 19,
                            Activo = true,
                            IdMenu = 19,
                            IdModule = 8
                        },
                        new
                        {
                            IdMenuModule = 20,
                            Activo = true,
                            IdMenu = 20,
                            IdModule = 8
                        });
                });

            modelBuilder.Entity("User.Domain.MenuRole", b =>
                {
                    b.Property<int>("IdMenuRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenuRol"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMenuRol");

                    b.ToTable("MenuRoles", "User");

                    b.HasData(
                        new
                        {
                            IdMenuRol = 1,
                            Activo = true,
                            IdMenu = 1,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 2,
                            Activo = true,
                            IdMenu = 2,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 3,
                            Activo = true,
                            IdMenu = 3,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 4,
                            Activo = true,
                            IdMenu = 4,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 5,
                            Activo = true,
                            IdMenu = 5,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 6,
                            Activo = true,
                            IdMenu = 6,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 7,
                            Activo = true,
                            IdMenu = 7,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 8,
                            Activo = true,
                            IdMenu = 8,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 9,
                            Activo = true,
                            IdMenu = 9,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 10,
                            Activo = true,
                            IdMenu = 10,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 11,
                            Activo = true,
                            IdMenu = 11,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 12,
                            Activo = true,
                            IdMenu = 12,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 13,
                            Activo = true,
                            IdMenu = 13,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 14,
                            Activo = true,
                            IdMenu = 14,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 15,
                            Activo = true,
                            IdMenu = 15,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 16,
                            Activo = true,
                            IdMenu = 16,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 17,
                            Activo = true,
                            IdMenu = 17,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 18,
                            Activo = true,
                            IdMenu = 18,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 19,
                            Activo = true,
                            IdMenu = 19,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdMenuRol = 20,
                            Activo = true,
                            IdMenu = 20,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        });
                });

            modelBuilder.Entity("User.Domain.MenuUser", b =>
                {
                    b.Property<int>("IdMenuUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenuUser"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdMenu")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMenuUser");

                    b.ToTable("MenuUsers", "User");
                });

            modelBuilder.Entity("User.Domain.Module", b =>
                {
                    b.Property<int>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModule"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("IdModulePadre")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModule");

                    b.ToTable("Modules", "User");

                    b.HasData(
                        new
                        {
                            IdModule = 1,
                            Activo = true,
                            IdModulePadre = 1,
                            Name = "tablero_control"
                        },
                        new
                        {
                            IdModule = 2,
                            Activo = true,
                            IdModulePadre = 2,
                            Name = "clientes"
                        },
                        new
                        {
                            IdModule = 3,
                            Activo = true,
                            IdModulePadre = 2,
                            Name = "clientes:nuevo"
                        },
                        new
                        {
                            IdModule = 4,
                            Activo = true,
                            IdModulePadre = 2,
                            Name = "clientes:lista"
                        },
                        new
                        {
                            IdModule = 5,
                            Activo = true,
                            IdModulePadre = 5,
                            Name = "productos"
                        },
                        new
                        {
                            IdModule = 6,
                            Activo = true,
                            IdModulePadre = 5,
                            Name = "productos:nuevo"
                        },
                        new
                        {
                            IdModule = 7,
                            Activo = true,
                            IdModulePadre = 5,
                            Name = "productos:lista"
                        },
                        new
                        {
                            IdModule = 8,
                            Activo = true,
                            IdModulePadre = 8,
                            Name = "seguridad"
                        },
                        new
                        {
                            IdModule = 9,
                            Activo = true,
                            IdModulePadre = 8,
                            Name = "seguridad:usuarios"
                        },
                        new
                        {
                            IdModule = 10,
                            Activo = true,
                            IdModulePadre = 9,
                            Name = "seguridad:usuarios:nuevo"
                        },
                        new
                        {
                            IdModule = 11,
                            Activo = true,
                            IdModulePadre = 9,
                            Name = "seguridad:usuarios:lista"
                        },
                        new
                        {
                            IdModule = 12,
                            Activo = true,
                            IdModulePadre = 8,
                            Name = "seguridad:menus"
                        },
                        new
                        {
                            IdModule = 13,
                            Activo = true,
                            IdModulePadre = 12,
                            Name = "seguridad:menus:nuevo"
                        },
                        new
                        {
                            IdModule = 14,
                            Activo = true,
                            IdModulePadre = 12,
                            Name = "seguridad:menus:lista"
                        },
                        new
                        {
                            IdModule = 15,
                            Activo = true,
                            IdModulePadre = 12,
                            Name = "seguridad:menus:menus_rol"
                        },
                        new
                        {
                            IdModule = 16,
                            Activo = true,
                            IdModulePadre = 15,
                            Name = "seguridad:menus:menus_rol:lista"
                        },
                        new
                        {
                            IdModule = 17,
                            Activo = true,
                            IdModulePadre = 8,
                            Name = "seguridad:roles"
                        },
                        new
                        {
                            IdModule = 18,
                            Activo = true,
                            IdModulePadre = 17,
                            Name = "seguridad:roles:nuevo"
                        },
                        new
                        {
                            IdModule = 19,
                            Activo = true,
                            IdModulePadre = 17,
                            Name = "seguridad:roles:lista"
                        });
                });

            modelBuilder.Entity("User.Domain.ModuleRole", b =>
                {
                    b.Property<int>("IdModuleRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModuleRol"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowEliminate")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowModify")
                        .HasColumnType("bit");

                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.Property<string>("IdRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModuleRol");

                    b.ToTable("ModuleRoles", "User");

                    b.HasData(
                        new
                        {
                            IdModuleRol = 1,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 1,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 2,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 2,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 3,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 3,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 4,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 4,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 5,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 5,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 6,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 6,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 7,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 7,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        },
                        new
                        {
                            IdModuleRol = 8,
                            Activo = true,
                            AllowCreate = true,
                            AllowEliminate = true,
                            AllowModify = true,
                            IdModule = 8,
                            IdRol = "178cb4b8-f8a4-45a6-b0dc-0c4f93f8aadb"
                        });
                });

            modelBuilder.Entity("User.Domain.ModuleUser", b =>
                {
                    b.Property<int>("IdModuleUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModuleUser"), 1L, 1);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowEliminate")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowModify")
                        .HasColumnType("bit");

                    b.Property<int>("IdModule")
                        .HasColumnType("int");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModuleUser");

                    b.ToTable("ModuleUsers", "User");
                });
#pragma warning restore 612, 618
        }
    }
}
